FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /app

COPY realtime-chat-api.csproj ./

RUN dotnet restore

COPY . .

RUN dotnet build -c Release -o /app/build

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final

WORKDIR /app

COPY --from=publish /app/publish .

EXPOSE 7200
EXPOSE 5090

ENTRYPOINT [ "dotnet","realtime-chat-api.dll" ]
